moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_manage_controllers: false

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller
  allowed_execution_duration_scaling: 2.0  # Gives 2x more time than planned
  allowed_goal_duration_margin: 0.5
  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint6
